const contacts = [
  {
    firstName: "Melek",
    lastName: "Abuqasim",
    fullName: "Melek Abuqasim",
    type: "partner",
    subType: "girlfriend",
    birthday: new Date("2007-07-26"),
    birthYear: 2007,
    nationality: "Palestinian",
    location: "Sapanca, Turkey",
    languages: "Turkish, Arabic, English",
    whatsapp: "+90...",
    bio: "Palestinian origin, raised in Saudi Arabia and Turkey. Studying dentistry, targets Hacettepe University. Speaks Turkish, Arabic, English; wants to learn Spanish. Known each other 4+ years, complex history.",
    relationshipHealth: "strong",
    followUpFrequency: "daily",
    isKeyPerson: true,
    importantDates: [
      { date: "2025-02-14", label: "Valentine's Day" },
    ],
  },
  {
    firstName: "Father",
    lastName: null,
    fullName: "Father",
    type: "family",
    subType: "father",
    birthday: new Date("1975-01-01"),
    birthYear: 1975,
    nationality: "Sudanese",
    location: "Riyadh, Saudi Arabia",
    languages: "Arabic, English",
    whatsapp: "+966...",
    bio: "Financial supporter (RM 2,088/mo), business partner (Gari, TeraMotors, Arslan). Key relationship for income and family duty.",
    relationshipHealth: "good",
    followUpFrequency: "weekly",
    isKeyPerson: true,
  },
  {
    firstName: "Aunt",
    lastName: null,
    fullName: "Aunt",
    type: "family",
    subType: "aunt",
    birthday: new Date("1970-06-15"),
    nationality: "Sudanese",
    location: "Kuala Lumpur, Malaysia",
    languages: "Arabic",
    bio: "Quran teacher and spiritual accountability partner. Lives in KL, provides family connection locally.",
    relationshipHealth: "strong",
    followUpFrequency: "weekly",
    isKeyPerson: true,
  },
  {
    firstName: "Jumana",
    lastName: null,
    fullName: "Jumana",
    type: "family",
    subType: "sister",
    nationality: "Sudanese",
    location: "Riyadh, Saudi Arabia",
    languages: "Arabic, English",
    bio: "Sister. Friend of Melek. Family connection in Saudi Arabia.",
    relationshipHealth: "good",
    followUpFrequency: "weekly",
    isKeyPerson: false,
  },
];

export default contacts;
