const DEFAULT_HABITS = [
  {
    name: "Fajr Prayer",
    frequency: "daily",
    targetCount: 1,
    timeOfDay: "fajr",
    isNonNegotiable: true,
    streakOn: true,
    category: "faith",
  },
  {
    name: "Dhuhr Prayer",
    frequency: "daily",
    targetCount: 1,
    timeOfDay: "dhuhr",
    isNonNegotiable: true,
    streakOn: true,
    category: "faith",
  },
  {
    name: "Asr Prayer",
    frequency: "daily",
    targetCount: 1,
    timeOfDay: "asr",
    isNonNegotiable: true,
    streakOn: true,
    category: "faith",
  },
  {
    name: "Maghrib Prayer",
    frequency: "daily",
    targetCount: 1,
    timeOfDay: "maghrib",
    isNonNegotiable: true,
    streakOn: true,
    category: "faith",
  },
  {
    name: "Isha Prayer",
    frequency: "daily",
    targetCount: 1,
    timeOfDay: "isha",
    isNonNegotiable: true,
    streakOn: true,
    category: "faith",
  },
  {
    name: "Morning Gym",
    frequency: "daily",
    targetCount: 1,
    timeOfDay: "morning",
    isNonNegotiable: true,
    streakOn: true,
    category: "health",
  },
  {
    name: "Quran Memorization",
    frequency: "daily",
    targetCount: 1,
    targetValue: 1,
    targetUnit: "pages",
    streakOn: true,
    category: "faith",
  },
  {
    name: "French Study",
    frequency: "daily",
    targetCount: 1,
    targetValue: 15,
    targetUnit: "minutes",
    streakOn: true,
    category: "education",
  },
  {
    name: "Sleep Protocol",
    frequency: "daily",
    targetCount: 1,
    timeOfDay: "night",
    isNonNegotiable: true,
    streakOn: true,
    category: "health",
  },
  {
    name: "No Deep Work Sunday",
    frequency: "weekly",
    targetCount: 1,
    isNonNegotiable: true,
    category: "lifestyle",
  },
  {
    name: "Weekly Review",
    frequency: "weekly",
    targetCount: 1,
    category: "productivity",
  },
  {
    name: "Malay Study",
    frequency: "daily",
    targetCount: 1,
    targetValue: 15,
    targetUnit: "minutes",
    category: "education",
  },
  {
    name: "Spanish Study",
    frequency: "daily",
    targetCount: 1,
    targetValue: 10,
    targetUnit: "minutes",
    category: "education",
  },
];

export default DEFAULT_HABITS;
