const projects = [
  {
    name: "VantLaunch",
    description: "Product studio building internal tools and SaaS for repair shops. Target: RM 1,500-5,000/client.",
    type: "agency",
    status: "building",
    revenueModel: "project_based",
    mrr: 0,
    arr: 0,
    totalRevenue: 0,
    pipelineStages: ["Lead", "Contacted", "Call Booked", "Proposal", "Won", "Lost"],
    activeDeals: 0,
    dealsWon: 0,
    dealValue: 0,
    stack: "Next.js 16, Prisma, PostgreSQL, Framer Motion",
    priority: 1,
    nextAction: "Send 5 outreach DMs to KL repair shops",
    weeklyGoal: "Book 2 discovery calls",
    color: "var(--rose)",
    icon: "🔴",
    notes: "Current outreach phase. Using The Firm agents to research leads and generate DMs. Target first client by July 2026.",
  },
  {
    name: "Gari",
    description: "SaaS marketplace connecting car owners with trusted mechanics in Saudi Arabia.",
    type: "saas",
    status: "maintenance",
    revenueModel: "subscription",
    mrr: 10000, // $100 in cents
    arr: 120000, // $1,200 in cents
    totalRevenue: 50000,
    stack: "Expo, Hono.js, Bun, Prisma, PostgreSQL",
    priority: 3,
    nextAction: "Fix workshop onboarding flow bug",
    color: "var(--gold)",
    icon: "🟡",
    notes: "87-95% complete. Currently underpaid at ~$100/mo. Needs pricing restructure or exit strategy.",
  },
  {
    name: "SpeakBill",
    description: "SaaS to simplify Malaysian parliamentary bills through AI summaries.",
    type: "saas",
    status: "launched",
    revenueModel: "subscription",
    mrr: 0,
    arr: 0,
    totalRevenue: 0,
    stack: "Next.js, AI/LLM integration",
    priority: 4,
    nextAction: "Monitor Product Hunt launch results",
    color: "var(--emerald)",
    icon: "🟢",
    notes: "Launched on Product Hunt. Currently in observe mode — no active development.",
  },
  {
    name: "The Firm",
    description: "Multi-agent internal platform for automating business operations across VantLaunch projects.",
    type: "internal_tool",
    status: "active",
    revenueModel: "none",
    mrr: 0,
    arr: 0,
    totalRevenue: 0,
    stack: "Next.js 16, 8 specialized agents, port 3010",
    port: 3010,
    priority: 3,
    nextAction: "Test COO agent chain for outreach automation",
    color: "var(--text-tertiary)",
    icon: "⚪",
    notes: "8 agents running: CEO (router), COO, CTO, CMO, research agent, outreach agent, legal agent, analytics agent. Manual launch required.",
  },
  {
    name: "TeraMotors",
    description: "Client app for automotive marketplace in Saudi Arabia.",
    type: "client_app",
    status: "maintenance",
    revenueModel: "project_based",
    mrr: 0,
    arr: 0,
    totalRevenue: 0,
    stack: "React Native, Node.js",
    repoUrl: "https://github.com/almonzer-fadl/teramotors",
    priority: 2,
    nextAction: "Fix critical bug — invoice PDF generation",
    color: "var(--accent)",
    icon: "🔵",
    notes: "~70% done, live in Saudi. Part of father's support system. Critical bugs remain.",
  },
  {
    name: "Project Origin",
    description: "Long-term vision: off-grid intentional community in Uruguay. Target: $250-430K to acquire land and establish infrastructure.",
    type: "personal_vision",
    status: "ideation",
    priority: 5,
    icon: "🌍",
    notes: "10-year grand strategy milestone. Combines sovereignty, self-sufficiency, and community building.",
  },
  {
    name: "Project Zenith",
    description: "Personal digital ecosystem — unified dashboard for all personal data, projects, and agents.",
    type: "personal_vision",
    status: "ideation",
    priority: 5,
    icon: "🌐",
    notes: "The meta-project that encompasses all other projects. Life OS is the first iteration.",
  },
];

export default projects;
